---
title: "Creating and Evaluating Seasonal Influenza Thresholds in Philadelphia"
subtitle: "BMIN5030 Final Project"
author: "Hope Schreiber"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers. Feel free to change the theme and other display settings, although this is not required.

## Overview {#sec-overview}

The goal of this project is to explore two popular methods for determining intensity thresholds for seasonal in Pennsylvania. The data utilized will be from the CDC's FluVIew Interactive database \[1\]. This is an online tool that provides publicly available, weekly ILI data at the state level. The overall purpose of this project is to apply the methods to Penn's own community, with the help of Sidney P and Kendra T (Epidemiologist and Data Analyst on the Public Health team at Penn Wellness). They have provided guidance on data organization and visualization, as well as dissemination of results.

[BMIN5030 Final Project GitHub Repository](https://github.com/HopeSch01/BMIN5030_Final_Project_Schreiber)

## Introduction {#sec-introduction}

To capture influenza (flu) season severity both actively and retrospectively, the Center for Disease Control and Prevention (CDC) uses intensity thresholds \[2\]. An intensity threshold is established from data gathered during previous flu seasons, and is then used to assess how severe the current flu season is in comparison \[2\]. They help researchers decide how severe flu activity is during peak flu season, and how severe the season was as a whole once it is finished. This information helps to guide public health action such as targeted messaging and prevention measures.

There is not a "gold standard" for calculating intensity thresholds, and multiple methods exist. In 2012, the World Health Organization (WHO) established a new method for defining flu flu thresholds \[3\]. It utilizes means and standard deviation from historical flu data, and the WHO released a standard guide for determining seasonal and alert thresholds \[4\]. The moving epidemic model (MEM) is another method for calculating influenza intensity thresholds. It also uses historical data, but involves more statistics and relies heavily on consecutive seasons of data \[5\]. An R package has been created to guide MEM use \[6\].

The CDC collaborates with state health departments and other clinical laboratories to maintain the U.S. influenza surveillance system \[1\]. Information on outpatient visits is reported by partners through the Influenza-like Illness Surveillance Network (ILINet) \[1\]. More than 110 million patient visits were reported during the 2022-23 season \[1\]. This is where the Public Health Team at Penn Wellness reports weekly ILI cases among students. With robust historical data available, seasonal flu thresholds can be established in Pennsylvannia to better understand current flu activity. Additionally, this provides an opportunity to compare two popular methods in establishing thresholds. This is a project that is rooted in the core epidemiological task of surveillance, but also includes statistical modeling skills and relevance to virology. Information from this project can help inform seasonal flu thresholds on UPenn's own campus. The Public Health Team at Penn Wellness collects weekly flu data, and maintains historical flu data spanning back to 2009. There is an opportunity for this project to have a real impact on our own campus community.

## Methods {#sec-methods}

Describe the data used and general methodological approach used to address the problem described in the @sec-introduction. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.

## Results {#sec-results}

Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

## Conclusion

This the conclusion. The @sec-results can be invoked here.
